device id validator and boot-time validator enhancements
xmidt-org/interpreter pull request #18
Opened 2021-04-30 23:25 UTC by j-mai

2021-05-04 01:36 UTC, kristinapathak requested changes
Overall, looks good! Had a few ideas to improve it a bit more.

2021-05-04 01:36 UTC, kristinapathak commented on validation/validator.go
> +func BootTimeValidator(tv TimeValidation, lastValidYear int) ValidatorFunc {
Can checking that the boot time is later than the last valid year be a `TimeValidation`?  Either we can make the current implementation of `TimeValidation` more configurable or make a second implementation of it.

2021-05-04 01:36 UTC, kristinapathak commented on validation/validator.go
> +			return false, InvalidEventErr{OriginalErr: ErrInconsistentDeviceID, ErrorTag: InconsistentDeviceID}
The error returned from this function is always the same - should we make it a variable either within the function or as a sentinel error at the top of the file?

2021-05-04 01:36 UTC, kristinapathak commented on validation/validator.go
> +func ConsistentDeviceIDValidator() ValidatorFunc {
If we find false positives with this function, it may be difficult to figure out what the problem is.  One solution to this would be to keep a list of all ids seen, and include it as a part of the error returned.  This would require checking everything, even after it fails.  Another solution might be including where we found a mismatched device id in the error, such as in the source or metadata key `whatever`.  Then slightly more information is exported and can be logged or included as needed by consumers of this library.

2021-05-04 01:36 UTC, kristinapathak commented on validation/validator.go
> +			return false, InvalidEventErr{OriginalErr: ErrInconsistentDeviceID, ErrorTag: InconsistentDeviceID}
This may not be needed given changes made based on my above suggestion.

2021-05-04 01:36 UTC, kristinapathak commented on validation/validator.go
> +// BootLengthValidator returns a ValidatorFunc that validates that the all unix timestamps
```suggestion
// BootLengthValidator returns a ValidatorFunc that validates that all unix timestamps
```

2021-05-04 01:36 UTC, kristinapathak commented on validation/validator.go
> +		bootTime := time.Unix(bootTimeInt, 0)
It looks like both times `getBootTime()` is called, we convert it to a `time.Time`.  Can we have `getBootTime()` do that for us?

2021-05-04 01:36 UTC, kristinapathak commented on validation/validator.go
> +					return false, InvalidEventErr{OriginalErr: ErrFastBoot, ErrorTag: FastBoot}
Similar to my suggestion above, do we want to include the boot time and destination time that led us to believe there is an issue?

Also - do we want to include every destination time that is potentially too fast?

2021-05-05 23:46 UTC, j-mai commented on validation/validator.go
> +func BootTimeValidator(tv TimeValidation, lastValidYear int) ValidatorFunc {
Good point! While fixing this, I had a hard time deciding whether to accept a TimeValidation as a second parameter that validates the year part or to have a new `type TimeValidators []TimeValidation` that has a `Valid` function, making it implement the `TimeValidation` interface. Then users can pass in any number of time validators that they want to validate the boot-time with. With this option, I had a hard time deciding whether to run all of the validators and if so, what to do if multiple validators returned errors, so I decided to go with the two parameters option but would love to hear your thoughts on this! :)

2021-05-06 19:16 UTC, kristinapathak approved these changes
Looks good! Just one suggestion/question.

2021-05-06 19:16 UTC, kristinapathak commented on validation/validator.go
> +			ids = append(ids, m[0])
Won't `ids` have a lot of duplicates?  Is it being deduped somewhere?

2021-05-06 19:17 UTC, kristinapathak commented on validation/validator.go
> +func BootTimeValidator(tv TimeValidation, lastValidYear int) ValidatorFunc {
I think what you did is a good solution for now.  Later, if we want more `TimeValidation`, this will be easy to update.

2021-05-06 20:55 UTC, j-mai commented on validation/validator.go
> +			ids = append(ids, m[0])
good point, saving them to a map and then changing that to an array if an error occurs is probably better.

2021-05-06 20:58 UTC, merged