Cycle validator example
xmidt-org/interpreter pull request #30
Opened 2021-06-04 21:57 UTC by j-mai

Add cycle validators as a cmd program.

2021-06-28 23:30 UTC, kristinapathak requested changes
Good start! Left some suggestions and questions.

2021-06-28 23:30 UTC, kristinapathak commented on cmd/cycleValidators/cycleValidators.go
> +func createValidators(config Config) []history.CycleValidatorFunc {
I don't think this needs the whole config? Just the validator list.

2021-06-28 23:30 UTC, kristinapathak commented on cmd/cycleValidators/cycleValidators.go
> +			readCommandLine,
Personally, I would call `runValidators()` from here, and write a little bit for our multierror, so just one error is returned (then the formatting in `printErrors()` would just be part of our special error's `Error()` func).

2021-06-28 23:30 UTC, kristinapathak commented on cmd/cycleValidators/cycleValidators.go
> +		os.Exit(1)
`os.Exit()` shouldn't be needed in a function called within the uber.fx framework.  My suggestion is either remove the `os.Exit()`s and return an error, or don't use uber.fx. 🙂 I've asked John in the past about using uber fx in a CLI and his answer was something like "it's up to you"...so you if you don't want to use uber fx, that's fine with me.

2021-06-28 23:30 UTC, kristinapathak commented on cmd/cycleValidators/cycleValidators.go
> +func main() {
So it's easier to find the main function, I think this file should be called `main.go`.

2021-06-28 23:30 UTC, kristinapathak commented on cmd/cycleValidators/cycleValidators.go
> +	}
Now that I've seen the validator configuration, I can see that it wouldn't work well as a flag.  I think the rest of what I suggested is still a good idea though.

2021-06-28 23:30 UTC, kristinapathak commented on cmd/cycleValidators/go.mod
> +module github.com/xmidt-org/interpreter/cmd/cycleValidators
We already talked but leaving a comment here - CLIs in the `cmd/` dir shouldn't have their own go mods.

2021-06-28 23:30 UTC, kristinapathak commented on cmd/eventsParser/eventsParser.go
>  package main
I have similar comments for this file as I put for `cmd/cycleValidators/cycleValidators.go`; I don't think I need to write them again. 😅 Once it's updated, I can check again...

2021-06-28 23:30 UTC, kristinapathak commented on cmd/cycleValidators/cycleValidators.go
> +	if err = json.Unmarshal(data, &events); err != nil {
We should decode using [`wrp-go`](https://pkg.go.dev/github.com/xmidt-org/wrp-go@v1.3.4/wrp).

2021-06-28 23:30 UTC, kristinapathak commented on cmd/parseAndValidate/events.json
> +[
Are these `events.json` files different? Would it make sense to have some `cmd/event-samples` dir with all of them in it and named somehow to describe what they provide?

2021-06-28 23:30 UTC, kristinapathak commented on cmd/parseAndValidate/parseAndValidate.go
> +package main
What's the benefit of having multiple `cmd`s rather than one that can be configured or have sub commands that cover each of these use cases? These `cmd`s all seem pretty similar and/or build on each other, right? What do you think?

2021-07-02 18:29 UTC, j-mai commented on cmd/parseAndValidate/parseAndValidate.go
> +package main
Yeah I think sub commands make sense

2021-07-02 18:41 UTC, j-mai commented on cmd/cycleValidators/cycleValidators.go
> +	if err = json.Unmarshal(data, &events); err != nil {
Since this is decoding into a list of `interpreter.Event` and not a list of `wrp.Message`, would using `wrp-go` still work? Wouldn't we lose the Birthdate since that isn't part of the `wrp.Message` struct?

2021-07-02 18:57 UTC, j-mai commented on cmd/parseAndValidate/events.json
> +[
I don't think it's necessary to have different events.json files (especially since there is a file generator tool included in the tools directory) so I'll just have one.

2021-07-09 00:25 UTC, kristinapathak commented on cmd/cycleValidators/cycleValidators.go
> +	if err = json.Unmarshal(data, &events); err != nil {
Oops, you're right...the benefit of the way wrp-go decodes is it's more efficient than `json.Unmarshal`.  I think we can try to make this more efficient later 👍

2021-07-09 05:11 UTC, kristinapathak approved these changes
This looks awesome! Left a few questions but the next step is to have Wes try it out. 🙂

2021-07-09 05:11 UTC, kristinapathak commented on cmd/getEvents.go
> +			}
Is there somewhere in the command help information that explains how this works? Or can we prompt for an id before trying to read from stdin?

2021-07-09 05:11 UTC, kristinapathak commented on cmd/getEvents.go
> +	data, err := ioutil.ReadFile(fmt.Sprintf("./%s", fileName))
I don't think we should add to the filename - why not just make it a filepath and allow the file to be anywhere?

2021-07-09 05:11 UTC, kristinapathak commented on cmd/root.go
> +	rootCmd.PersistentFlags().BoolVarP(&useRebootParser, "reboot", "r", false, "parse just reboot events")
Is this needed for every command? Or just certain sub commands?

2021-07-09 22:40 UTC, j-mai commented on cmd/getEvents.go
> +			}
I think prompting is a good idea!

2021-07-09 22:41 UTC, j-mai commented on cmd/root.go
> +	rootCmd.PersistentFlags().BoolVarP(&useRebootParser, "reboot", "r", false, "parse just reboot events")
Just certain commands-I've moved them to the init function of the appropriate command.

2021-07-09 22:54 UTC, merged